version: '3.9'
services:
  moodledb:
    image: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - moodle-network
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=debian-sys-maint
      - MYSQL_PASSWORD=vaIdfgRPSXzKbPPd
      - MYSQL_DATABASE=moodle

  moodle:
    image: bitnami/moodle:4.1
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./moodle:/bitnami/moodledata
    networks:
      - moodle-network
    environment:
      - MOODLE_DATABASE_HOST=moodledb
      - MOODLE_DATABASE_USER=debian-sys-maint
      - MOODLE_DATABASE_PASSWORD=vaIdfgRPSXzKbPPd
      - MOODLE_DATABASE_NAME=moodle

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 88:80
    environment:
      - PMA_HOST=moodledb
    networks:
      - moodle-network

volumes:
  mariadb-data:
  moodle-data:

networks:
  moodle-network: